### ISSUE TITLE
bwtestserver fails when no paths are available

### ISSUE THREAD

**Issue by hausheer** [perrig/scionlab#26] opened 2018-03-09 17:40 UTC
bwtestserver fails and exits when there are no paths available. 
`EROR[03-09|17:32:38] Unable to find path                      src=1-1026 dst=3-1034 code="No paths available"`
`2018-03-09T17:32:38.437+0000 [CRIT] Fatal error. Exiting. LOG15_ERROR="Key(common.BasicError) is not a string: Dispatcher error`
`    Path not found srcIA="1-1026" dstIA="3-1034"" LOG15_ERROR="Normalized odd number of arguments by adding nil"`
`exit status 1`
Currently this problem arises frequently when running bwtests across several ISDs. In subsequent runs, paths can usually be found. bwtest should not exit.

**Comment by FR4NK-W** [comment] 2018-03-12 15:40
Duplicate of #17 
Fixed incidentally by PR #25 and more explicitly by PR #28

**Closed** 2018-03-12 22:48 UTC
